services:
  - type: web
    name: badya-university-chatbot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: FLASK_ENV
        value: production
